# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_NAME = ENV['BOX_NAME'] || "lucid32"
BOX_URI = ENV['BOX_URI'] || "http://files.vagrantup.com/lucid32.box"


Vagrant::Config.run do |config|
  config.vm.box = BOX_NAME
  config.vm.box_url = BOX_URI
  config.vm.forward_port  80, 8080
  config.vm.forward_port  9999, 9999

   config.vm.provision :chef_solo do |chef|
     chef.cookbooks_path = "cookbooks"
     chef.roles_path = "roles"
     chef.add_role "all"
   end
end